id: 48b2c239438b48ebb2353afe35821c27
initial_creation_type: ocr
source_metadata:
  volumes:
    7ff7fc05450f49d28b5fa2c7f83073da:
      base_file: v097.txt
      image_group_id: I1PD95942
      title: ''
      total_pages: 1198
      volume_number: 97
